# Generated by Django 4.2.10 on 2026-02-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_alter_vote_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("SPEAKER", "Speaker"),
                    ("EVALUATOR", "Evaluator"),
                    ("TABLE_TOPICS", "Table Topics Speaker"),
                ],
                max_length=20,
            ),
        ),
    ]
